#!/usr/bin/env bash
if [[ $1 = -h || $1 = --help || -z $1 ]]; then
  echo "usage: $0 files..."
  exit
fi

script='
dd < "${BASH_SOURCE-$0}" skip=3 bs=512 2>/dev/null | tar x
exit
'

# create a fake tar archive that just happens to be a valid shell script
# https://en.wikipedia.org/wiki/Tar_(computing)
{
                                  #Field Offset  Field Size  Field
  printf %-100s $'#!/bin/sh\n#'   #           0         100  File name
  printf %-8s   0                 #         100           8  File mode
  printf %-8s   0                 #         108           8  Owner's numeric user ID
  printf %-8s   0                 #         116           8  Group's numeric user ID
  printf %-12o  "${#script}"      #         124          12  File size in bytes (octal base)
  printf %-12s  0                 #         136          12  Last modification time in numeric Unix time format (octal)
  printf %-8s   '        '        #         148           8  Checksum for header record
  # K == "this is a long linkname for the next entry"
  printf %-1s   K                 #         156           1  Link indicator (file type)
  printf %-100s                   #         157         100  Name of linked file
  printf %-255s

} > archive.sh

# checksum == sum (as unsigned ints) of all the bytes in the header
checksum=$(
  od -An -tu1 -v archive.sh |
  tr -s ' \n' + |
  sed 's/^+//;s/+$/\n/' |
  bc
)

# overwrite the bytes in the right position
printf '%-8o' "$checksum" |
dd seek=148 bs=1 count=8 conv=notrunc of=archive.sh 2>/dev/null





printf %-512s "$script" >>archive.sh
chmod +x archive.sh



# add a second entry with an empty filename
checksum=$( {
printf \\0%99s
printf %-8s   0
printf %-8s   0
printf %-8s   0
printf %-12o  0
printf %-12s  0
printf %-8s   '        '
printf %-1s   V
printf %-100s
printf %-255s
} | od -An -tu1 -v | tr -s ' \n' + | sed 's/^+//;s/+$/\n/' | bc)
{
printf \\0%99s
printf %-8s   0
printf %-8s   0
printf %-8s   0
printf %-12o  0
printf %-12s  0
printf %-8o   "$checksum"
# V == "this is a volume header" (thus, this entry is ignored while extracting)
printf %-1s   V
printf %-100s
printf %-255s
} >>archive.sh


# now we can append our files normally
tar rf archive.sh "$@"
